var searchData=
[
  ['ecv_5fcustom_0',['ECV_CUSTOM',['../_e_c_v__c_u_s_t_o_m.html',1,'expansion_CV']]],
  ['ecv_5flinear_1',['ECV_LINEAR',['../_e_c_v__l_i_n_e_a_r.html',1,'expansion_CV']]],
  ['ecv_5fmultithermal_2',['ECV_MULTITHERMAL',['../_e_c_v__m_u_l_t_i_t_h_e_r_m_a_l.html',1,'expansion_CV']]],
  ['ecv_5fmultithermal_5fmultibaric_3',['ECV_MULTITHERMAL_MULTIBARIC',['../_e_c_v__m_u_l_t_i_t_h_e_r_m_a_l__m_u_l_t_i_b_a_r_i_c.html',1,'expansion_CV']]],
  ['ecv_5fumbrellas_5ffile_4',['ECV_UMBRELLAS_FILE',['../_e_c_v__u_m_b_r_e_l_l_a_s__f_i_l_e.html',1,'expansion_CV']]],
  ['ecv_5fumbrellas_5fline_5',['ECV_UMBRELLAS_LINE',['../_e_c_v__u_m_b_r_e_l_l_a_s__l_i_n_e.html',1,'expansion_CV']]],
  ['eds_6',['EDS',['../_e_d_s.html',1,'EDSMODBias']]],
  ['eefsolv_7',['EEFSOLV',['../_e_e_f_s_o_l_v.html',1,'Colvar']]],
  ['effective_5fenergy_5fdrift_8',['EFFECTIVE_ENERGY_DRIFT',['../_e_f_f_e_c_t_i_v_e__e_n_e_r_g_y__d_r_i_f_t.html',1,'MTS']]],
  ['embed_20a_20separate_20plumed_20instance_9',['Embed a separate PLUMED instance',['../embed.html',1,'Miscellaneous']]],
  ['emmi_10',['EMMI',['../_e_m_m_i.html',1,'ISDBColvar']]],
  ['emmivox_11',['EMMIVOX',['../_e_m_m_i_v_o_x.html',1,'ISDBColvar']]],
  ['endplumed_12',['ENDPLUMED',['../_e_n_d_p_l_u_m_e_d.html',1,'comments']]],
  ['energy_13',['ENERGY',['../_e_n_e_r_g_y.html',1,'Colvar']]],
  ['enhanced_20sampling_14',['OPES (On-the-fly Probability Enhanced Sampling)',['../_o_p_e_s.html',1,'AddMod']]],
  ['enhanced_20sampling_20ves_20code_15',['Variationally Enhanced Sampling (VES code)',['../_v_e_s.html',1,'AddMod']]],
  ['ensemble_16',['ENSEMBLE',['../_e_n_s_e_m_b_l_e.html',1,'Function']]],
  ['environmentsimilarity_17',['ENVIRONMENTSIMILARITY',['../_e_n_v_i_r_o_n_m_e_n_t_s_i_m_i_l_a_r_i_t_y.html',1,'mcolv']]],
  ['ermsd_18',['ERMSD',['../_e_r_m_s_d.html',1,'Colvar']]],
  ['euclidean_5fdistance_19',['EUCLIDEAN_DISTANCE',['../_e_u_c_l_i_d_e_a_n__d_i_s_t_a_n_c_e.html',1,'mcolv']]],
  ['evaluate_5ffunction_5ffrom_5fgrid_20',['EVALUATE_FUNCTION_FROM_GRID',['../_e_v_a_l_u_a_t_e__f_u_n_c_t_i_o_n__f_r_o_m__g_r_i_d.html',1,'Analysis']]],
  ['evaluate_5ffunction_5ffrom_5fgrid_5fscalar_21',['EVALUATE_FUNCTION_FROM_GRID_SCALAR',['../_e_v_a_l_u_a_t_e__f_u_n_c_t_i_o_n__f_r_o_m__g_r_i_d__s_c_a_l_a_r.html',1,'Analysis']]],
  ['evaluate_5ffunction_5ffrom_5fgrid_5fvector_22',['EVALUATE_FUNCTION_FROM_GRID_VECTOR',['../_e_v_a_l_u_a_t_e__f_u_n_c_t_i_o_n__f_r_o_m__g_r_i_d__v_e_c_t_o_r.html',1,'Analysis']]],
  ['example_20of_20logmfd_23',['Example of LogMFD',['../_l_o_g_m_f_d.html#Example-LoGMFD',1,'']]],
  ['example_20of_20logpd_24',['Example of LogPD',['../_l_o_g_m_f_d.html#Example-LogPD',1,'']]],
  ['examples_25',['Examples',['../_b_a_i_e_s.html#autotoc_md81',1,'Examples'],['../_l_o_g_m_f_d.html#Examples',1,'Examples']]],
  ['exchange_26',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['exchange_20patterns_20in_20replica_20exchange_27',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['expansion_20collective_20variables_28',['Expansion Collective Variables',['../expansion__c_v.html',1,'OPES']]],
  ['experiment_20directed_20simulation_29',['Experiment Directed Simulation',['../_e_d_s_m_o_d.html',1,'AddMod']]],
  ['exploiting_20contact_20matrices_30',['Exploiting contact matrices',['../contactmatrix.html',1,'colvarintro']]],
  ['expressions_31',['Regular Expressions',['../_regex.html',1,'misc']]],
  ['extended_20system_20adaptive_20biasing_20force_32',['Extended-System Adaptive Biasing Force',['../_e_a_b_f_m_o_d.html',1,'AddMod']]],
  ['extended_5flagrangian_33',['EXTENDED_LAGRANGIAN',['../_e_x_t_e_n_d_e_d__l_a_g_r_a_n_g_i_a_n.html',1,'Bias']]],
  ['external_34',['EXTERNAL',['../_e_x_t_e_r_n_a_l.html',1,'Bias']]],
  ['extracting_20all_20the_20base_20quantities_35',['Extracting all the base quantities',['../mcolv.html#usingbase',1,'']]],
  ['extracv_36',['EXTRACV',['../_e_x_t_r_a_c_v.html',1,'Colvar']]]
];
