var searchData=
[
  ['calculating_20dissimilarity_20matrices_0',['Calculating dissimilarity matrices',['../_analysis.html#dissimilaritym',1,'']]],
  ['caliber_1',['CALIBER',['../_c_a_l_i_b_e_r.html',1,'ISDBBias']]],
  ['cavity_2',['CAVITY',['../_c_a_v_i_t_y.html',1,'mcolv']]],
  ['cavity_5fcalc_3',['CAVITY_CALC',['../_c_a_v_i_t_y__c_a_l_c.html',1,'mcolv']]],
  ['cell_4',['CELL',['../_c_e_l_l.html',1,'Colvar']]],
  ['center_5',['CENTER',['../_c_e_n_t_e_r.html',1,'Group']]],
  ['center_5ffast_6',['CENTER_FAST',['../_c_e_n_t_e_r__f_a_s_t.html',1,'Group']]],
  ['change_20log_7',['Change Log',['../_change_log.html',1,'']]],
  ['changing_20exchange_20patterns_20in_20replica_20exchange_8',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['charge_9',['CHARGE',['../_c_h_a_r_g_e.html',1,'mcolv']]],
  ['charge_5fscalar_10',['CHARGE_SCALAR',['../_c_h_a_r_g_e__s_c_a_l_a_r.html',1,'mcolv']]],
  ['charge_5fvector_11',['CHARGE_VECTOR',['../_c_h_a_r_g_e__v_e_c_t_o_r.html',1,'mcolv']]],
  ['classical_5fmds_12',['CLASSICAL_MDS',['../_c_l_a_s_s_i_c_a_l__m_d_s.html',1,'Analysis']]],
  ['cluster_13',['Installing PLUMED on a cluster',['../_installation.html#installingonacluster',1,'']]],
  ['cluster_5fdiameter_14',['CLUSTER_DIAMETER',['../_c_l_u_s_t_e_r__d_i_a_m_e_t_e_r.html',1,'contactmatrix']]],
  ['cluster_5fdistribution_15',['CLUSTER_DISTRIBUTION',['../_c_l_u_s_t_e_r__d_i_s_t_r_i_b_u_t_i_o_n.html',1,'contactmatrix']]],
  ['cluster_5fdistribution_5fcalc_16',['CLUSTER_DISTRIBUTION_CALC',['../_c_l_u_s_t_e_r__d_i_s_t_r_i_b_u_t_i_o_n__c_a_l_c.html',1,'contactmatrix']]],
  ['cluster_5fnatoms_17',['CLUSTER_NATOMS',['../_c_l_u_s_t_e_r__n_a_t_o_m_s.html',1,'contactmatrix']]],
  ['cluster_5fproperties_18',['CLUSTER_PROPERTIES',['../_c_l_u_s_t_e_r__p_r_o_p_e_r_t_i_e_s.html',1,'contactmatrix']]],
  ['cluster_5fweights_19',['CLUSTER_WEIGHTS',['../_c_l_u_s_t_e_r__w_e_i_g_h_t_s.html',1,'contactmatrix']]],
  ['cluster_5fwithsurface_20',['CLUSTER_WITHSURFACE',['../_c_l_u_s_t_e_r__w_i_t_h_s_u_r_f_a_c_e.html',1,'contactmatrix']]],
  ['code_21',['code',['../degub.html',1,'Debugging the code'],['../_installation.html#Patching',1,'Patching your MD code'],['../_v_e_s.html',1,'Variationally Enhanced Sampling (VES code)']]],
  ['code_20specific_20notes_22',['Code specific notes',['../_code_specific_notes.html',1,'Installation']]],
  ['codes_20interfaced_20with_20plumed_23',['Codes interfaced with PLUMED',['../index.html#codes',1,'']]],
  ['collect_24',['COLLECT',['../_c_o_l_l_e_c_t.html',1,'']]],
  ['collect_5fframes_25',['COLLECT_FRAMES',['../_c_o_l_l_e_c_t__f_r_a_m_e_s.html',1,'Analysis']]],
  ['collective_20variable_26',['collective variable',['../_p_i_v_m_o_d.html',1,'PIV collective variable'],['../_s2_c_m_m_o_d.html',1,'S2 contact model collective variable'],['../_s_a_s_a_m_o_d.html',1,'SASA collective variable'],['../sizeshape_m_o_d.html',1,'sizeshape collective variable']]],
  ['collective_20variables_27',['Collective Variables',['../colvarintro.html',1,'Collective Variables'],['../expansion__c_v.html',1,'Expansion Collective Variables']]],
  ['com_28',['COM',['../_c_o_m.html',1,'Group']]],
  ['combine_29',['COMBINE',['../_c_o_m_b_i_n_e.html',1,'Function']]],
  ['combine_5fmatrix_30',['COMBINE_MATRIX',['../_c_o_m_b_i_n_e__m_a_t_r_i_x.html',1,'Colvar']]],
  ['combine_5fscalar_31',['COMBINE_SCALAR',['../_c_o_m_b_i_n_e__s_c_a_l_a_r.html',1,'Function']]],
  ['combine_5fvector_32',['COMBINE_VECTOR',['../_c_o_m_b_i_n_e__v_e_c_t_o_r.html',1,'Function']]],
  ['command_20line_20tools_33',['Command Line Tools',['../_e_a_b_f_m_o_d_c_l_tools.html',1,'Command Line Tools'],['../ves_cltools.html',1,'Command Line Tools'],['../tools.html',1,'Command Line Tools']]],
  ['comments_34',['Comments',['../comments.html',1,'Miscellaneous']]],
  ['committor_35',['COMMITTOR',['../_c_o_m_m_i_t_t_o_r.html',1,'Analysis']]],
  ['compilers_36',['Supported compilers',['../_installation.html#SupportedCompilers',1,'']]],
  ['compiling_37',['Cross compiling',['../_installation.html#CrossCompiling',1,'']]],
  ['compiling_20plumed_38',['Compiling PLUMED',['../_installation.html#CompilingPlumed',1,'']]],
  ['completion_39',['completion',['../completion.html',1,'tools']]],
  ['concatenate_40',['CONCATENATE',['../_c_o_n_c_a_t_e_n_a_t_e.html',1,'mcolv']]],
  ['conda_41',['conda',['../_installation.html#Installation-conda',1,'Installing PLUMED with conda'],['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md77',1,'Using conda']]],
  ['config_42',['config',['../config.html',1,'tools']]],
  ['configurations_43',['Distances from reference configurations',['../dists.html',1,'colvarintro']]],
  ['configuring_20plumed_44',['Configuring PLUMED',['../_installation.html#ConfiguringPlumed',1,'']]],
  ['constant_45',['CONSTANT',['../_c_o_n_s_t_a_n_t.html',1,'Colvar']]],
  ['constants_46',['Parsing constants',['../parsing-constants.html',1,'Miscellaneous']]],
  ['contact_20matrices_47',['Exploiting contact matrices',['../contactmatrix.html',1,'colvarintro']]],
  ['contact_20model_20collective_20variable_48',['S2 contact model collective variable',['../_s2_c_m_m_o_d.html',1,'AddMod']]],
  ['contact_5fmatrix_49',['CONTACT_MATRIX',['../_c_o_n_t_a_c_t__m_a_t_r_i_x.html',1,'contactmatrix']]],
  ['contact_5fmatrix_5fproper_50',['CONTACT_MATRIX_PROPER',['../_c_o_n_t_a_c_t__m_a_t_r_i_x__p_r_o_p_e_r.html',1,'contactmatrix']]],
  ['contactmap_51',['CONTACTMAP',['../_c_o_n_t_a_c_t_m_a_p.html',1,'Colvar']]],
  ['contents_52',['Contents',['../sizeshape_m_o_d.html#Module',1,'Contents'],['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md80',1,'Module Contents']]],
  ['continuation_20lines_53',['Continuation lines',['../_continuation_lines.html',1,'Miscellaneous']]],
  ['convert_5fto_5ffes_54',['CONVERT_TO_FES',['../_c_o_n_v_e_r_t__t_o__f_e_s.html',1,'Analysis']]],
  ['coord_5fangles_55',['COORD_ANGLES',['../_c_o_o_r_d__a_n_g_l_e_s.html',1,'mcolv']]],
  ['coordination_56',['COORDINATION',['../_c_o_o_r_d_i_n_a_t_i_o_n.html',1,'Colvar']]],
  ['coordination_5fmoments_57',['COORDINATION_MOMENTS',['../_c_o_o_r_d_i_n_a_t_i_o_n__m_o_m_e_n_t_s.html',1,'mcolv']]],
  ['coordination_5fshell_5faverage_58',['COORDINATION_SHELL_AVERAGE',['../_c_o_o_r_d_i_n_a_t_i_o_n__s_h_e_l_l__a_v_e_r_a_g_e.html',1,'mcolv']]],
  ['coordination_5fshell_5ffunction_59',['COORDINATION_SHELL_FUNCTION',['../_c_o_o_r_d_i_n_a_t_i_o_n__s_h_e_l_l__f_u_n_c_t_i_o_n.html',1,'mcolv']]],
  ['coordinationnumber_60',['COORDINATIONNUMBER',['../_c_o_o_r_d_i_n_a_t_i_o_n_n_u_m_b_e_r.html',1,'mcolv']]],
  ['covariance_5fmatrix_61',['COVARIANCE_MATRIX',['../_c_o_v_a_r_i_a_n_c_e__m_a_t_r_i_x.html',1,'Analysis']]],
  ['create_5fmask_62',['CREATE_MASK',['../_c_r_e_a_t_e__m_a_s_k.html',1,'Analysis']]],
  ['cross_20compiling_63',['Cross compiling',['../_installation.html#CrossCompiling',1,'']]],
  ['cs2backbone_64',['CS2BACKBONE',['../_c_s2_b_a_c_k_b_o_n_e.html',1,'ISDBColvar']]],
  ['custom_65',['CUSTOM',['../_c_u_s_t_o_m.html',1,'Function']]],
  ['custom_5fgrid_66',['CUSTOM_GRID',['../_c_u_s_t_o_m__g_r_i_d.html',1,'Analysis']]],
  ['custom_5fmatrix_67',['CUSTOM_MATRIX',['../_c_u_s_t_o_m__m_a_t_r_i_x.html',1,'Colvar']]],
  ['custom_5fscalar_68',['CUSTOM_SCALAR',['../_c_u_s_t_o_m__s_c_a_l_a_r.html',1,'Function']]],
  ['custom_5fvector_69',['CUSTOM_VECTOR',['../_c_u_s_t_o_m__v_e_c_t_o_r.html',1,'Function']]],
  ['cv_20documentation_70',['CV Documentation',['../_colvar.html',1,'colvarintro']]],
  ['cv_20documentation_71',['CV documentation',['../funnel_cv.html',1,'FUNNELMOD']]],
  ['cvs_20documentation_72',['CVs Documentation',['../_i_s_d_b_colvar.html',1,'CVs Documentation'],['../_m_e_m_b_r_a_n_e_f_u_s_i_o_n_m_o_d_colvar.html',1,'CVs Documentation'],['../_p_i_v_m_o_d_colvar.html',1,'CVs Documentation'],['../_s2_c_m_m_o_d_colvar.html',1,'CVs Documentation'],['../_s_a_s_a_m_o_d_colvar.html',1,'CVs Documentation'],['../sizeshape_m_o_d_colvar.html',1,'CVs Documentation']]],
  ['cylindrical_5fharmonic_73',['CYLINDRICAL_HARMONIC',['../_c_y_l_i_n_d_r_i_c_a_l__h_a_r_m_o_n_i_c.html',1,'mcolv']]],
  ['cylindrical_5fharmonic_5fmatrix_74',['CYLINDRICAL_HARMONIC_MATRIX',['../_c_y_l_i_n_d_r_i_c_a_l__h_a_r_m_o_n_i_c__m_a_t_r_i_x.html',1,'mcolv']]]
];
