var searchData=
[
  ['a_20cluster_0',['Installing PLUMED on a cluster',['../_installation.html#installingonacluster',1,'']]],
  ['a_20separate_20plumed_20instance_1',['Embed a separate PLUMED instance',['../embed.html',1,'Miscellaneous']]],
  ['a_20thermostat_2',['Using LogMFD/PD with a thermostat',['../_l_o_g_m_f_d.html#Thermostat',1,'']]],
  ['abmd_3',['ABMD',['../_a_b_m_d.html',1,'Bias']]],
  ['about_20this_20manual_4',['About this manual',['../index.html#AboutManual',1,'']]],
  ['accumulate_5',['ACCUMULATE',['../_a_c_c_u_m_u_l_a_t_e.html',1,'Analysis']]],
  ['actions_6',['Index of Actions',['../glossary.html',1,'']]],
  ['actions_7',['Full list of actions',['../glossary.html#ActionList',1,'']]],
  ['actions_20documentation_8',['General Actions Documentation',['../_i_s_d_b_generic.html',1,'ISDB']]],
  ['adaptive_20biasing_20force_9',['Extended-System Adaptive Biasing Force',['../_e_a_b_f_m_o_d.html',1,'AddMod']]],
  ['adaptive_5fpath_10',['ADAPTIVE_PATH',['../_a_d_a_p_t_i_v_e__p_a_t_h.html',1,'Colvar']]],
  ['additional_20modules_11',['Additional Modules',['../_add_mod.html',1,'Additional Modules'],['../_installation.html#additional-modules',1,'Additional Modules']]],
  ['algorithms_12',['Outputting the results from analysis algorithms',['../_analysis.html#output',1,'']]],
  ['all_20the_20base_20quantities_13',['Extracting all the base quantities',['../mcolv.html#usingbase',1,'']]],
  ['alphabeta_14',['ALPHABETA',['../_a_l_p_h_a_b_e_t_a.html',1,'mcolv']]],
  ['alpharmsd_15',['ALPHARMSD',['../_a_l_p_h_a_r_m_s_d.html',1,'Colvar']]],
  ['analysis_16',['Analysis',['../_analysis.html',1,'']]],
  ['analysis_17',['Storing data for analysis',['../_analysis.html#storing',1,'']]],
  ['analysis_20algorithms_18',['Outputting the results from analysis algorithms',['../_analysis.html#output',1,'']]],
  ['and_20averaging_19',['Reweighting and Averaging',['../_analysis.html#analysisbias',1,'']]],
  ['and_20lapack_20',['BLAS and LAPACK',['../_installation.html#BlasAndLapack',1,'']]],
  ['and_20pbc_21',['Broken Molecules and PBC',['../_group.html#pbc',1,'']]],
  ['and_20plumed_20with_20gpu_22',['GROMACS and PLUMED with GPU',['../_g_m_x_g_p_u.html',1,'Performances']]],
  ['and_20virtual_20atoms_23',['Groups and Virtual Atoms',['../_group.html',1,'colvarintro']]],
  ['angle_24',['ANGLE',['../_a_n_g_l_e.html',1,'Colvar']]],
  ['angle_5fscalar_25',['ANGLE_SCALAR',['../_a_n_g_l_e__s_c_a_l_a_r.html',1,'Colvar']]],
  ['angle_5fvector_26',['ANGLE_VECTOR',['../_a_n_g_l_e__v_e_c_t_o_r.html',1,'Colvar']]],
  ['angles_27',['ANGLES',['../_a_n_g_l_e_s.html',1,'Colvar']]],
  ['ann_28',['ANN',['../_a_n_n.html',1,'ANNMODFunction']]],
  ['ann_20artificial_20neural_20network_20function_29',['ANN (Artificial Neural Network) function',['../_a_n_n_m_o_d.html',1,'AddMod']]],
  ['antibetarmsd_30',['ANTIBETARMSD',['../_a_n_t_i_b_e_t_a_r_m_s_d.html',1,'Colvar']]],
  ['apr_201_202019_31',['Apr 1 2019',['../_c_h_a_n_g_e_s-2-4.html#autotoc_md35',1,'Version 2.4.5 (Apr 1, 2019)'],['../_c_h_a_n_g_e_s-2-5.html#autotoc_md40',1,'Version 2.5.1 (Apr 1, 2019)']]],
  ['apr_2013_202016_32',['Version 2.2.2 (Apr 13, 2016)',['../_c_h_a_n_g_e_s-2-2.html#autotoc_md17',1,'']]],
  ['apr_2016_202021_33',['Apr 16 2021',['../_c_h_a_n_g_e_s-2-5.html#autotoc_md46',1,'Version 2.5.7 (Apr 16, 2021)'],['../_c_h_a_n_g_e_s-2-6.html#autotoc_md50',1,'Version 2.6.3 (Apr 16, 2021)'],['../_c_h_a_n_g_e_s-2-7.html#autotoc_md55',1,'Version 2.7.1 (Apr 16, 2021)']]],
  ['args2vatom_34',['ARGS2VATOM',['../_a_r_g_s2_v_a_t_o_m.html',1,'Group']]],
  ['around_35',['AROUND',['../_a_r_o_u_n_d.html',1,'mcolv']]],
  ['around_5fcalc_36',['AROUND_CALC',['../_a_r_o_u_n_d__c_a_l_c.html',1,'mcolv']]],
  ['arrange_5fpoints_37',['ARRANGE_POINTS',['../_a_r_r_a_n_g_e__p_o_i_n_t_s.html',1,'Analysis']]],
  ['artificial_20neural_20network_20function_38',['ANN (Artificial Neural Network) function',['../_a_n_n_m_o_d.html',1,'AddMod']]],
  ['atomic_5fsmac_39',['ATOMIC_SMAC',['../_a_t_o_m_i_c__s_m_a_c.html',1,'mcolv']]],
  ['atoms_40',['Atoms',['../_group.html',1,'Groups and Virtual Atoms'],['../_group.html#atomSpecs',1,'Specifying Atoms'],['../_group.html#vatoms',1,'Virtual Atoms']]],
  ['aug_2025_202025_41',['Version 2.10 (Aug 25, 2025)',['../_c_h_a_n_g_e_s-2-10.html#autotoc_md12',1,'']]],
  ['autocompletion_42',['Using bash autocompletion',['../_bash_autocompletion.html',1,'Miscellaneous']]],
  ['average_43',['AVERAGE',['../_a_v_e_r_a_g_e.html',1,'Analysis']]],
  ['average_5fpath_5fdisplacement_44',['AVERAGE_PATH_DISPLACEMENT',['../_a_v_e_r_a_g_e__p_a_t_h__d_i_s_p_l_a_c_e_m_e_n_t.html',1,'']]],
  ['averaging_45',['Reweighting and Averaging',['../_analysis.html#analysisbias',1,'']]]
];
