var searchData=
[
  ['random_5fexchanges_0',['RANDOM_EXCHANGES',['../_r_a_n_d_o_m__e_x_c_h_a_n_g_e_s.html',1,'exchange-patterns']]],
  ['rdc_1',['RDC',['../_r_d_c.html',1,'ISDBColvar']]],
  ['rdf_2',['RDF',['../_r_d_f.html',1,'']]],
  ['read_3',['READ',['../_r_e_a_d.html',1,'driver']]],
  ['readmasscharge_4',['READMASSCHARGE',['../_r_e_a_d_m_a_s_s_c_h_a_r_g_e.html',1,'Colvar']]],
  ['reduction_5',['Dimensionality Reduction',['../_analysis.html#dimred',1,'']]],
  ['reference_20configurations_6',['Distances from reference configurations',['../dists.html',1,'colvarintro']]],
  ['reference_5fgrid_7',['REFERENCE_GRID',['../_r_e_f_e_r_e_n_c_e__g_r_i_d.html',1,'Analysis']]],
  ['regular_20expressions_8',['Regular Expressions',['../_regex.html',1,'misc']]],
  ['reparameterize_5fpath_9',['REPARAMETERIZE_PATH',['../_r_e_p_a_r_a_m_e_t_e_r_i_z_e__p_a_t_h.html',1,'']]],
  ['replica_20exchange_10',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['replica_20suffix_11',['Replica suffix',['../_files.html#Replica-Suffix',1,'']]],
  ['replica_20syntax_12',['Special replica syntax',['../special-replica-syntax.html',1,'Miscellaneous']]],
  ['rescale_13',['RESCALE',['../_r_e_s_c_a_l_e.html',1,'ISDBBias']]],
  ['reset_5fcell_14',['RESET_CELL',['../_r_e_s_e_t__c_e_l_l.html',1,'Group']]],
  ['restart_15',['RESTART',['../_r_e_s_t_a_r_t.html',1,'Bias']]],
  ['restraint_16',['RESTRAINT',['../_r_e_s_t_r_a_i_n_t.html',1,'Bias']]],
  ['restraint_5fscalar_17',['RESTRAINT_SCALAR',['../_r_e_s_t_r_a_i_n_t__s_c_a_l_a_r.html',1,'Bias']]],
  ['results_20from_20analysis_20algorithms_18',['Outputting the results from analysis algorithms',['../_analysis.html#output',1,'']]],
  ['reweight_5fbias_19',['REWEIGHT_BIAS',['../_r_e_w_e_i_g_h_t__b_i_a_s.html',1,'Analysis']]],
  ['reweight_5fmetad_20',['REWEIGHT_METAD',['../_r_e_w_e_i_g_h_t__m_e_t_a_d.html',1,'Analysis']]],
  ['reweight_5ftemp_5fpress_21',['REWEIGHT_TEMP_PRESS',['../_r_e_w_e_i_g_h_t__t_e_m_p__p_r_e_s_s.html',1,'Analysis']]],
  ['reweighting_20and_20averaging_22',['Reweighting and Averaging',['../_analysis.html#analysisbias',1,'']]],
  ['rmsd_23',['RMSD',['../_r_m_s_d.html',1,'dists']]],
  ['rmsd_5fscalar_24',['RMSD_SCALAR',['../_r_m_s_d__s_c_a_l_a_r.html',1,'dists']]],
  ['rmsd_5fvector_25',['RMSD_VECTOR',['../_r_m_s_d__v_e_c_t_o_r.html',1,'dists']]],
  ['rops_26',['ROPS',['../_r_o_p_s.html',1,'Colvar']]]
];
