var searchData=
[
  ['macports_0',['Installing PLUMED with MacPorts',['../_installation.html#Installation-macports',1,'']]],
  ['mahalanobis_5fdistance_1',['MAHALANOBIS_DISTANCE',['../_m_a_h_a_l_a_n_o_b_i_s__d_i_s_t_a_n_c_e.html',1,'Function']]],
  ['making_20lepton_20library_20faster_2',['Making lepton library faster',['../_lepton.html',1,'Performances']]],
  ['manager_20tt_20pip_20tt_3',['Using Python&apos;s package manager (&lt;tt&gt;pip&lt;/tt&gt;)',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md76',1,'']]],
  ['manual_4',['manual',['../index.html#AboutManual',1,'About this manual'],['../manual.html',1,'manual']]],
  ['mar_2013_202023_5',['Mar 13 2023',['../_c_h_a_n_g_e_s-2-7.html#autotoc_md60',1,'Version 2.7.6 (Mar 13, 2023)'],['../_c_h_a_n_g_e_s-2-8.html#autotoc_md63',1,'Version 2.8.2 (Mar 13, 2023)']]],
  ['mar_2016_202015_6',['Version 2.1.2 (Mar 16, 2015)',['../_c_h_a_n_g_e_s-2-1.html#autotoc_md8',1,'']]],
  ['mar_202_202018_7',['Mar 2 2018',['../_c_h_a_n_g_e_s-2-3.html#autotoc_md26',1,'Version 2.3.5 (Mar 2, 2018)'],['../_c_h_a_n_g_e_s-2-4.html#autotoc_md31',1,'Version 2.4.1 (Mar 2, 2018)']]],
  ['mar_2031_202017_8',['Mar 31 2017',['../_c_h_a_n_g_e_s-2-2.html#autotoc_md20',1,'Version 2.2.5 (Mar 31, 2017)'],['../_c_h_a_n_g_e_s-2-3.html#autotoc_md22',1,'Version 2.3.1 (Mar 31, 2017)']]],
  ['marvel_20ves_20school_20february_202017_9',['MARVEL-VES School February 2017',['../ves_tutorial_lugano_2017.html',1,'ves_tutorials']]],
  ['mass_10',['MASS',['../_m_a_s_s.html',1,'mcolv']]],
  ['mass_5fscalar_11',['MASS_SCALAR',['../_m_a_s_s__s_c_a_l_a_r.html',1,'mcolv']]],
  ['mass_5fvector_12',['MASS_VECTOR',['../_m_a_s_s__v_e_c_t_o_r.html',1,'mcolv']]],
  ['matheval_13',['MATHEVAL',['../_m_a_t_h_e_v_a_l.html',1,'Function']]],
  ['matheval_5fgrid_14',['MATHEVAL_GRID',['../_m_a_t_h_e_v_a_l__g_r_i_d.html',1,'Analysis']]],
  ['matheval_5fmatrix_15',['MATHEVAL_MATRIX',['../_m_a_t_h_e_v_a_l__m_a_t_r_i_x.html',1,'Colvar']]],
  ['matheval_5fscalar_16',['MATHEVAL_SCALAR',['../_m_a_t_h_e_v_a_l__s_c_a_l_a_r.html',1,'Function']]],
  ['matheval_5fvector_17',['MATHEVAL_VECTOR',['../_m_a_t_h_e_v_a_l__v_e_c_t_o_r.html',1,'Function']]],
  ['matrices_18',['matrices',['../_analysis.html#dissimilaritym',1,'Calculating dissimilarity matrices'],['../contactmatrix.html',1,'Exploiting contact matrices']]],
  ['matrix_5fproduct_19',['MATRIX_PRODUCT',['../_m_a_t_r_i_x__p_r_o_d_u_c_t.html',1,'mcolv']]],
  ['matrix_5fproduct_5fdiagonal_20',['MATRIX_PRODUCT_DIAGONAL',['../_m_a_t_r_i_x__p_r_o_d_u_c_t__d_i_a_g_o_n_a_l.html',1,'Function']]],
  ['matrix_5fvector_5fproduct_21',['MATRIX_VECTOR_PRODUCT',['../_m_a_t_r_i_x__v_e_c_t_o_r__p_r_o_d_u_c_t.html',1,'mcolv']]],
  ['maxent_22',['MAXENT',['../_m_a_x_e_n_t.html',1,'Bias']]],
  ['may_2023_202025_23',['Version 2.9.4 (May 23, 2025)',['../_c_h_a_n_g_e_s-2-9.html#autotoc_md70',1,'']]],
  ['may_2025_202023_24',['May 25 2023',['../_c_h_a_n_g_e_s-2-8.html#autotoc_md64',1,'Version 2.8.3 (May 25, 2023)'],['../_c_h_a_n_g_e_s-2-9.html#autotoc_md66',1,'Version 2.9 (May 25, 2023)']]],
  ['maze_25',['MAZE',['../_m_a_z_e.html',1,'AddMod']]],
  ['maze_5floss_26',['MAZE_LOSS',['../_m_a_z_e__l_o_s_s.html',1,'maze_loss']]],
  ['maze_5fmemetic_5fsampling_27',['MAZE_MEMETIC_SAMPLING',['../_m_a_z_e__m_e_m_e_t_i_c__s_a_m_p_l_i_n_g.html',1,'maze_optimizer']]],
  ['maze_5foptimizer_5fbias_28',['MAZE_OPTIMIZER_BIAS',['../_m_a_z_e__o_p_t_i_m_i_z_e_r__b_i_a_s.html',1,'maze_bias']]],
  ['maze_5frandom_5facceleration_5fmd_29',['MAZE_RANDOM_ACCELERATION_MD',['../_m_a_z_e__r_a_n_d_o_m__a_c_c_e_l_e_r_a_t_i_o_n__m_d.html',1,'maze_optimizer']]],
  ['maze_5frandom_5fwalk_30',['MAZE_RANDOM_WALK',['../_m_a_z_e__r_a_n_d_o_m__w_a_l_k.html',1,'maze_optimizer']]],
  ['maze_5fsimulated_5fannealing_31',['MAZE_SIMULATED_ANNEALING',['../_m_a_z_e__s_i_m_u_l_a_t_e_d__a_n_n_e_a_l_i_n_g.html',1,'maze_optimizer']]],
  ['maze_5fsteered_5fmd_32',['MAZE_STEERED_MD',['../_m_a_z_e__s_t_e_e_r_e_d__m_d.html',1,'maze_optimizer']]],
  ['md_20code_33',['Patching your MD code',['../_installation.html#Patching',1,'']]],
  ['mean_34',['MEAN',['../_m_e_a_n.html',1,'Colvar']]],
  ['mean_20force_20dynamics_35',['Logarithmic Mean Force Dynamics',['../_l_o_g_m_f_d_m_o_d.html',1,'AddMod']]],
  ['mean_5fscalar_36',['MEAN_SCALAR',['../_m_e_a_n__s_c_a_l_a_r.html',1,'Colvar']]],
  ['mean_5fvector_37',['MEAN_VECTOR',['../_m_e_a_n__v_e_c_t_o_r.html',1,'Colvar']]],
  ['membrane_20fusion_38',['Membrane Fusion',['../_m_e_m_b_r_a_n_e_f_u_s_i_o_n_m_o_d.html',1,'AddMod']]],
  ['memfusionp_39',['MEMFUSIONP',['../_m_e_m_f_u_s_i_o_n_p.html',1,'MEMBRANEFUSIONMODColvar']]],
  ['metad_40',['METAD',['../_m_e_t_a_d.html',1,'Bias']]],
  ['metadynamics_41',['Metadynamics',['../_metadyn.html',1,'Performances']]],
  ['metadynamics_20fm_42',['Funnel-Metadynamics (FM)',['../_f_u_n_n_e_l_m_o_d.html',1,'AddMod']]],
  ['metainference_43',['METAINFERENCE',['../_m_e_t_a_i_n_f_e_r_e_n_c_e.html',1,'ISDBBias']]],
  ['metatensor_44',['Building plumed with metatensor',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md79',1,'']]],
  ['metatomic_45',['METATOMIC',['../_m_e_t_a_t_o_m_i_c.html',1,'METATOMICMOD']]],
  ['metatomic_46',['Metatomic',['../_m_e_t_a_t_o_m_i_c_m_o_d.html',1,'AddMod']]],
  ['method_20of_20optimization_47',['Method of optimization',['../_c_l_a_s_s_i_c_a_l__m_d_s.html#dim-sec',1,'']]],
  ['mfilter_5fless_48',['MFILTER_LESS',['../_m_f_i_l_t_e_r__l_e_s_s.html',1,'mcolv']]],
  ['mfilter_5fmore_49',['MFILTER_MORE',['../_m_f_i_l_t_e_r__m_o_r_e.html',1,'mcolv']]],
  ['miscellaneous_50',['Miscellaneous',['../_miscellaneous.html',1,'']]],
  ['mklib_51',['mklib',['../mklib.html',1,'tools']]],
  ['model_20collective_20variable_52',['S2 contact model collective variable',['../_s2_c_m_m_o_d.html',1,'AddMod']]],
  ['module_20contents_53',['Module Contents',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md80',1,'']]],
  ['modules_54',['Modules',['../_add_mod.html',1,'Additional Modules'],['../_installation.html#additional-modules',1,'Additional Modules']]],
  ['modules_55',['List of modules',['../mymodules.html',1,'Miscellaneous']]],
  ['molecules_56',['Molecules',['../_group.html#mols',1,'']]],
  ['molecules_20and_20pbc_57',['Broken Molecules and PBC',['../_group.html#pbc',1,'']]],
  ['molinfo_58',['MOLINFO',['../_m_o_l_i_n_f_o.html',1,'Group']]],
  ['moments_59',['MOMENTS',['../_m_o_m_e_n_t_s.html',1,'Function']]],
  ['moments_5fscalar_60',['MOMENTS_SCALAR',['../_m_o_m_e_n_t_s__s_c_a_l_a_r.html',1,'Function']]],
  ['moments_5fvector_61',['MOMENTS_VECTOR',['../_m_o_m_e_n_t_s__v_e_c_t_o_r.html',1,'Function']]],
  ['more_5fthan_62',['MORE_THAN',['../_m_o_r_e__t_h_a_n.html',1,'Function']]],
  ['more_5fthan_5fmatrix_63',['MORE_THAN_MATRIX',['../_m_o_r_e__t_h_a_n__m_a_t_r_i_x.html',1,'Colvar']]],
  ['more_5fthan_5fvector_64',['MORE_THAN_VECTOR',['../_m_o_r_e__t_h_a_n__v_e_c_t_o_r.html',1,'Function']]],
  ['movingrestraint_65',['MOVINGRESTRAINT',['../_m_o_v_i_n_g_r_e_s_t_r_a_i_n_t.html',1,'Bias']]],
  ['multi_5frmsd_66',['MULTI_RMSD',['../_m_u_l_t_i__r_m_s_d.html',1,'dists']]],
  ['multicolvar_67',['MultiColvar',['../mcolv.html',1,'colvarintro']]],
  ['multicolvar_68',['Multicolvar',['../_multicolvar.html',1,'Performances']]],
  ['multicolvar_20bias_69',['MultiColvar bias',['../mcolv.html#multicolvarbias',1,'']]],
  ['multicolvar_20functions_70',['MultiColvar functions',['../mcolv.html#multicolvarfunction',1,'']]],
  ['multicolvardens_71',['MULTICOLVARDENS',['../_m_u_l_t_i_c_o_l_v_a_r_d_e_n_s.html',1,'Analysis']]],
  ['multiple_20time_20stepping_72',['Multiple time stepping',['../_m_t_s.html',1,'Performances']]]
];
