var searchData=
[
  ['package_20manager_20tt_20pip_20tt_0',['Using Python&apos;s package manager (&lt;tt&gt;pip&lt;/tt&gt;)',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md76',1,'']]],
  ['pairentropies_1',['PAIRENTROPIES',['../_p_a_i_r_e_n_t_r_o_p_i_e_s.html',1,'mcolv']]],
  ['pairentropy_2',['PAIRENTROPY',['../_p_a_i_r_e_n_t_r_o_p_y.html',1,'mcolv']]],
  ['pamm_3',['PAMM',['../_p_a_m_m.html',1,'mcolv']]],
  ['parabetarmsd_4',['PARABETARMSD',['../_p_a_r_a_b_e_t_a_r_m_s_d.html',1,'Colvar']]],
  ['parsing_20constants_5',['Parsing constants',['../parsing-constants.html',1,'Miscellaneous']]],
  ['partial_5ftempering_6',['partial_tempering',['../partial_tempering.html',1,'tools']]],
  ['patch_7',['patch',['../patch.html',1,'tools']]],
  ['patching_20your_20md_20code_8',['Patching your MD code',['../_installation.html#Patching',1,'']]],
  ['path_9',['PATH',['../_p_a_t_h.html',1,'Colvar']]],
  ['pathmsd_10',['PATHMSD',['../_p_a_t_h_m_s_d.html',1,'Colvar']]],
  ['pathtools_11',['pathtools',['../pathtools.html',1,'tools']]],
  ['patterns_20in_20replica_20exchange_12',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['pbc_13',['PBC',['../_group.html#pbc',1,'Broken Molecules and PBC'],['../_p_b_c.html',1,'PBC']]],
  ['pbmetad_14',['PBMETAD',['../_p_b_m_e_t_a_d.html',1,'Bias']]],
  ['pca_15',['PCA',['../_p_c_a.html',1,'Analysis']]],
  ['pcarmsd_16',['PCARMSD',['../_p_c_a_r_m_s_d.html',1,'dists']]],
  ['pcavars_17',['PCAVARS',['../_p_c_a_v_a_r_s.html',1,'Colvar']]],
  ['pcs_18',['PCS',['../_p_c_s.html',1,'ISDBColvar']]],
  ['pd_19',['PD',['../_l_o_g_m_f_d.html#Nose-Hoover',1,'Nose-Hoover LogMFD/PD'],['../_l_o_g_m_f_d.html#VS',1,'Velocity scaling LogMFD/PD']]],
  ['pd_20with_20a_20thermostat_20',['Using LogMFD/PD with a thermostat',['../_l_o_g_m_f_d.html#Thermostat',1,'']]],
  ['pdb2constant_21',['PDB2CONSTANT',['../_p_d_b2_c_o_n_s_t_a_n_t.html',1,'Colvar']]],
  ['pdbreader_22',['pdbreader',['../pdbreader.html',1,'misc']]],
  ['pdbrenumber_23',['pdbrenumber',['../pdbrenumber.html',1,'tools']]],
  ['performances_24',['Performances',['../_performances.html',1,'']]],
  ['pesmd_25',['pesmd',['../pesmd.html',1,'tools']]],
  ['piecewise_26',['PIECEWISE',['../_p_i_e_c_e_w_i_s_e.html',1,'Function']]],
  ['piecewise_5fscalar_27',['PIECEWISE_SCALAR',['../_p_i_e_c_e_w_i_s_e__s_c_a_l_a_r.html',1,'Function']]],
  ['pip_20tt_28',['Using Python&apos;s package manager (&lt;tt&gt;pip&lt;/tt&gt;)',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md76',1,'']]],
  ['piv_29',['PIV',['../_p_i_v.html',1,'PIVMODColvar']]],
  ['piv_20collective_20variable_30',['PIV collective variable',['../_p_i_v_m_o_d.html',1,'AddMod']]],
  ['plane_31',['PLANE',['../_p_l_a_n_e.html',1,'Colvar']]],
  ['plane_5fscalar_32',['PLANE_SCALAR',['../_p_l_a_n_e__s_c_a_l_a_r.html',1,'Colvar']]],
  ['plane_5fvector_33',['PLANE_VECTOR',['../_p_l_a_n_e__v_e_c_t_o_r.html',1,'Colvar']]],
  ['planes_34',['PLANES',['../_p_l_a_n_e_s.html',1,'mcolv']]],
  ['plotswitch_35',['plotswitch',['../plotswitch.html',1,'tools']]],
  ['plugins_36',['VMD trajectory plugins',['../_installation.html#installation-vmdplugins',1,'']]],
  ['plumed_37',['PLUMED',['../index.html#codes',1,'Codes interfaced with PLUMED'],['../_installation.html#CompilingPlumed',1,'Compiling PLUMED'],['../_installation.html#ConfiguringPlumed',1,'Configuring PLUMED'],['../_installation.html#InstallingPlumed',1,'Installing PLUMED'],['../_installation.html#installingpython-outside',1,'Installing Python wrappers outside PLUMED'],['../_installation.html#installingpython-inside',1,'Installing Python wrappers within PLUMED'],['../_p_l_u_m_e_d.html',1,'PLUMED']]],
  ['plumed_20instance_38',['Embed a separate PLUMED instance',['../embed.html',1,'Miscellaneous']]],
  ['plumed_20isdb_39',['PLUMED-ISDB',['../_i_s_d_b.html',1,'AddMod']]],
  ['plumed_20on_20a_20cluster_40',['Installing PLUMED on a cluster',['../_installation.html#installingonacluster',1,'']]],
  ['plumed_20units_41',['Plumed units',['../_syntax.html#units',1,'']]],
  ['plumed_20with_20conda_42',['Installing PLUMED with conda',['../_installation.html#Installation-conda',1,'']]],
  ['plumed_20with_20gpu_43',['GROMACS and PLUMED with GPU',['../_g_m_x_g_p_u.html',1,'Performances']]],
  ['plumed_20with_20macports_44',['Installing PLUMED with MacPorts',['../_installation.html#Installation-macports',1,'']]],
  ['plumed_20with_20metatensor_45',['Building plumed with metatensor',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md79',1,'']]],
  ['position_46',['POSITION',['../_p_o_s_i_t_i_o_n.html',1,'Colvar']]],
  ['position_5fscalar_47',['POSITION_SCALAR',['../_p_o_s_i_t_i_o_n__s_c_a_l_a_r.html',1,'Colvar']]],
  ['position_5fvector_48',['POSITION_VECTOR',['../_p_o_s_i_t_i_o_n__v_e_c_t_o_r.html',1,'Colvar']]],
  ['pre_49',['PRE',['../_p_r_e.html',1,'ISDBColvar']]],
  ['print_50',['PRINT',['../_p_r_i_n_t.html',1,'Analysis']]],
  ['print_5fndx_51',['PRINT_NDX',['../_p_r_i_n_t__n_d_x.html',1,'Analysis']]],
  ['probability_20enhanced_20sampling_52',['OPES (On-the-fly Probability Enhanced Sampling)',['../_o_p_e_s.html',1,'AddMod']]],
  ['product_53',['PRODUCT',['../_p_r_o_d_u_c_t.html',1,'Function']]],
  ['progress_54',['progress',['../_c_h_a_n_g_e_s-2-10.html#autotoc_md14',1,'Version 2.10.2 (in progress)'],['../_c_h_a_n_g_e_s-2-9.html#autotoc_md72',1,'Version 2.9.6 (in progress)']]],
  ['project_5fpoints_55',['PROJECT_POINTS',['../_p_r_o_j_e_c_t__p_o_i_n_t_s.html',1,'Analysis']]],
  ['projection_5fon_5faxis_56',['PROJECTION_ON_AXIS',['../_p_r_o_j_e_c_t_i_o_n__o_n__a_x_i_s.html',1,'Colvar']]],
  ['propertymap_57',['PROPERTYMAP',['../_p_r_o_p_e_r_t_y_m_a_p.html',1,'Colvar']]],
  ['puckering_58',['PUCKERING',['../_p_u_c_k_e_r_i_n_g.html',1,'Colvar']]],
  ['put_59',['PUT',['../_p_u_t.html',1,'']]],
  ['python_20s_20package_20manager_20tt_20pip_20tt_60',['Using Python&apos;s package manager (&lt;tt&gt;pip&lt;/tt&gt;)',['../_m_e_t_a_t_o_m_i_c_m_o_d.html#autotoc_md76',1,'']]],
  ['python_20wrappers_61',['Installing Python wrappers',['../_installation.html#installingpython',1,'']]],
  ['python_20wrappers_20outside_20plumed_62',['Installing Python wrappers outside PLUMED',['../_installation.html#installingpython-outside',1,'']]],
  ['python_20wrappers_20within_20plumed_63',['Installing Python wrappers within PLUMED',['../_installation.html#installingpython-inside',1,'']]],
  ['pytorch_64',['PYTORCH',['../_p_y_t_o_r_c_h.html',1,'AddMod']]],
  ['pytorch_5fmodel_65',['PYTORCH_MODEL',['../_p_y_t_o_r_c_h__m_o_d_e_l.html',1,'PYTORCHFunction']]]
];
