var searchData=
[
  ['pairentropies_0',['PAIRENTROPIES',['../_p_a_i_r_e_n_t_r_o_p_i_e_s.html',1,'mcolv']]],
  ['pairentropy_1',['PAIRENTROPY',['../_p_a_i_r_e_n_t_r_o_p_y.html',1,'mcolv']]],
  ['pamm_2',['PAMM',['../_p_a_m_m.html',1,'mcolv']]],
  ['parabetarmsd_3',['PARABETARMSD',['../_p_a_r_a_b_e_t_a_r_m_s_d.html',1,'Colvar']]],
  ['parsing_20constants_4',['Parsing constants',['../parsing-constants.html',1,'Miscellaneous']]],
  ['partial_5ftempering_5',['partial_tempering',['../partial_tempering.html',1,'tools']]],
  ['patch_6',['patch',['../patch.html',1,'tools']]],
  ['path_7',['PATH',['../_p_a_t_h.html',1,'Colvar']]],
  ['pathmsd_8',['PATHMSD',['../_p_a_t_h_m_s_d.html',1,'Colvar']]],
  ['pathtools_9',['pathtools',['../pathtools.html',1,'tools']]],
  ['patterns_20in_20replica_20exchange_10',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['pbc_11',['PBC',['../_p_b_c.html',1,'']]],
  ['pbmetad_12',['PBMETAD',['../_p_b_m_e_t_a_d.html',1,'Bias']]],
  ['pca_13',['PCA',['../_p_c_a.html',1,'Analysis']]],
  ['pcarmsd_14',['PCARMSD',['../_p_c_a_r_m_s_d.html',1,'dists']]],
  ['pcavars_15',['PCAVARS',['../_p_c_a_v_a_r_s.html',1,'Colvar']]],
  ['pcs_16',['PCS',['../_p_c_s.html',1,'ISDBColvar']]],
  ['pdb2constant_17',['PDB2CONSTANT',['../_p_d_b2_c_o_n_s_t_a_n_t.html',1,'Colvar']]],
  ['pdbreader_18',['pdbreader',['../pdbreader.html',1,'misc']]],
  ['pdbrenumber_19',['pdbrenumber',['../pdbrenumber.html',1,'tools']]],
  ['performances_20',['Performances',['../_performances.html',1,'']]],
  ['pesmd_21',['pesmd',['../pesmd.html',1,'tools']]],
  ['piecewise_22',['PIECEWISE',['../_p_i_e_c_e_w_i_s_e.html',1,'Function']]],
  ['piecewise_5fscalar_23',['PIECEWISE_SCALAR',['../_p_i_e_c_e_w_i_s_e__s_c_a_l_a_r.html',1,'Function']]],
  ['piv_24',['PIV',['../_p_i_v.html',1,'PIVMODColvar']]],
  ['piv_20collective_20variable_25',['PIV collective variable',['../_p_i_v_m_o_d.html',1,'AddMod']]],
  ['plane_26',['PLANE',['../_p_l_a_n_e.html',1,'Colvar']]],
  ['plane_5fscalar_27',['PLANE_SCALAR',['../_p_l_a_n_e__s_c_a_l_a_r.html',1,'Colvar']]],
  ['plane_5fvector_28',['PLANE_VECTOR',['../_p_l_a_n_e__v_e_c_t_o_r.html',1,'Colvar']]],
  ['planes_29',['PLANES',['../_p_l_a_n_e_s.html',1,'mcolv']]],
  ['plotswitch_30',['plotswitch',['../plotswitch.html',1,'tools']]],
  ['plumed_31',['PLUMED',['../_p_l_u_m_e_d.html',1,'embed']]],
  ['plumed_20instance_32',['Embed a separate PLUMED instance',['../embed.html',1,'Miscellaneous']]],
  ['plumed_20isdb_33',['PLUMED-ISDB',['../_i_s_d_b.html',1,'AddMod']]],
  ['plumed_20with_20gpu_34',['GROMACS and PLUMED with GPU',['../_g_m_x_g_p_u.html',1,'Performances']]],
  ['position_35',['POSITION',['../_p_o_s_i_t_i_o_n.html',1,'Colvar']]],
  ['position_5fscalar_36',['POSITION_SCALAR',['../_p_o_s_i_t_i_o_n__s_c_a_l_a_r.html',1,'Colvar']]],
  ['position_5fvector_37',['POSITION_VECTOR',['../_p_o_s_i_t_i_o_n__v_e_c_t_o_r.html',1,'Colvar']]],
  ['pre_38',['PRE',['../_p_r_e.html',1,'ISDBColvar']]],
  ['print_39',['PRINT',['../_p_r_i_n_t.html',1,'Analysis']]],
  ['print_5fndx_40',['PRINT_NDX',['../_p_r_i_n_t__n_d_x.html',1,'Analysis']]],
  ['probability_20enhanced_20sampling_41',['OPES (On-the-fly Probability Enhanced Sampling)',['../_o_p_e_s.html',1,'AddMod']]],
  ['product_42',['PRODUCT',['../_p_r_o_d_u_c_t.html',1,'Function']]],
  ['project_5fpoints_43',['PROJECT_POINTS',['../_p_r_o_j_e_c_t__p_o_i_n_t_s.html',1,'Analysis']]],
  ['projection_5fon_5faxis_44',['PROJECTION_ON_AXIS',['../_p_r_o_j_e_c_t_i_o_n__o_n__a_x_i_s.html',1,'Colvar']]],
  ['propertymap_45',['PROPERTYMAP',['../_p_r_o_p_e_r_t_y_m_a_p.html',1,'Colvar']]],
  ['puckering_46',['PUCKERING',['../_p_u_c_k_e_r_i_n_g.html',1,'Colvar']]],
  ['put_47',['PUT',['../_p_u_t.html',1,'']]],
  ['pytorch_48',['PYTORCH',['../_p_y_t_o_r_c_h.html',1,'AddMod']]],
  ['pytorch_5fmodel_49',['PYTORCH_MODEL',['../_p_y_t_o_r_c_h__m_o_d_e_l.html',1,'PYTORCHFunction']]]
];
