var searchData=
[
  ['random_5fexchanges_0',['RANDOM_EXCHANGES',['../_r_a_n_d_o_m__e_x_c_h_a_n_g_e_s.html',1,'exchange-patterns']]],
  ['rdc_1',['RDC',['../_r_d_c.html',1,'ISDBColvar']]],
  ['rdf_2',['RDF',['../_r_d_f.html',1,'']]],
  ['read_3',['READ',['../_r_e_a_d.html',1,'driver']]],
  ['readmasscharge_4',['READMASSCHARGE',['../_r_e_a_d_m_a_s_s_c_h_a_r_g_e.html',1,'Colvar']]],
  ['reference_20configurations_5',['Distances from reference configurations',['../dists.html',1,'colvarintro']]],
  ['reference_5fgrid_6',['REFERENCE_GRID',['../_r_e_f_e_r_e_n_c_e__g_r_i_d.html',1,'Analysis']]],
  ['regular_20expressions_7',['Regular Expressions',['../_regex.html',1,'misc']]],
  ['reparameterize_5fpath_8',['REPARAMETERIZE_PATH',['../_r_e_p_a_r_a_m_e_t_e_r_i_z_e__p_a_t_h.html',1,'']]],
  ['replica_20exchange_9',['Changing exchange patterns in replica exchange',['../exchange-patterns.html',1,'Miscellaneous']]],
  ['replica_20syntax_10',['Special replica syntax',['../special-replica-syntax.html',1,'Miscellaneous']]],
  ['rescale_11',['RESCALE',['../_r_e_s_c_a_l_e.html',1,'ISDBBias']]],
  ['reset_5fcell_12',['RESET_CELL',['../_r_e_s_e_t__c_e_l_l.html',1,'Group']]],
  ['restart_13',['RESTART',['../_r_e_s_t_a_r_t.html',1,'Bias']]],
  ['restraint_14',['RESTRAINT',['../_r_e_s_t_r_a_i_n_t.html',1,'Bias']]],
  ['restraint_5fscalar_15',['RESTRAINT_SCALAR',['../_r_e_s_t_r_a_i_n_t__s_c_a_l_a_r.html',1,'Bias']]],
  ['reweight_5fbias_16',['REWEIGHT_BIAS',['../_r_e_w_e_i_g_h_t__b_i_a_s.html',1,'Analysis']]],
  ['reweight_5fmetad_17',['REWEIGHT_METAD',['../_r_e_w_e_i_g_h_t__m_e_t_a_d.html',1,'Analysis']]],
  ['reweight_5ftemp_5fpress_18',['REWEIGHT_TEMP_PRESS',['../_r_e_w_e_i_g_h_t__t_e_m_p__p_r_e_s_s.html',1,'Analysis']]],
  ['rmsd_19',['RMSD',['../_r_m_s_d.html',1,'dists']]],
  ['rmsd_5fscalar_20',['RMSD_SCALAR',['../_r_m_s_d__s_c_a_l_a_r.html',1,'dists']]],
  ['rmsd_5fvector_21',['RMSD_VECTOR',['../_r_m_s_d__v_e_c_t_o_r.html',1,'dists']]],
  ['rops_22',['ROPS',['../_r_o_p_s.html',1,'Colvar']]]
];
